Adopt json api
aiidateam/aiida-restapi pull request #18
Opened 2021-06-03 22:25 UTC by ltalirz

2021-06-03 22:31 UTC, ltalirz commented
@chrisjsewell I've explicitly excluded the vendored `json_api.py` from the mypy checks, yet the pre-commit still complains about it.
Can you please tell me how to fix this?

2021-06-03 22:51 UTC, ltalirz commented
We'll also need to decide whether to make the response fully JSON API compliant - would be straightforward but would definitely mean having to edit all response processing of existing clients (since the data moves from `data` to `data -> attributes`

2021-06-03 23:03 UTC, chrisjsewell commented
> @chrisjsewell I've explicitly excluded the vendored json_api.py from the mypy checks, yet the pre-commit still complains about it.

So I imagine you want something like this in the mypy.ini:

```
[mypy-aiida_restapi.json_api]
check_untyped_defs = False
```

2021-06-03 23:10 UTC, chrisjsewell commented
>  would be straightforward but would definitely mean having to edit all response processing of existing clients (since the data moves from data to data -> attributes).
Perhaps we start without it for the time being...

Well I guess if we are going to make breaking changes, lets not be shy about it lol. I think it is better if possible to have one major change that clients can deal with in one go, rather than multiple stages of changes

2021-06-03 23:10 UTC, chrisjsewell commented on .pre-commit-config.yaml
> +      - pydantic-jsonapi==0.11.0
why pinned to a single version?

2021-06-03 23:15 UTC, chrisjsewell commented on aiida_restapi/models/__init__.py
> +from .entities import *
Err, I'm not really a fan of `*` imports, I think explicit is better. Like we've seen with aiida-core, you can end up with sub-classes clobbering namespaces.
I'm open to a discussion on what the best practice is though (is there some PEP that advocates for this?)

2021-06-03 23:19 UTC, chrisjsewell requested changes
thanks @ltalirz, looks like a good standardised approach 👌
just a few minor questions

2025-12-22 07:53 UTC, edan-bainglass commented
@ltalirz thanks for initiating this. I recently wrapped up several major updates in this PR that build on the pydantic models of aiida-core (see https://github.com/aiidateam/aiida-core/pull/6990). My plan is to now do what you aimed to do here. However, it is likely easier to implement it from scratch, considering the changes. As such, I will open a PR superseding this one and tag you there.

2026-07-30 05:28 UTC, edan-bainglass commented
Superseded by #101 and related PRs

2026-07-30 05:32 UTC, closed without merging