📚 DOCS: Tutorial on Launching a WorkChain
aiidateam/aiida-restapi pull request #31
Opened 2021-12-09 15:27 UTC by flavianojs

Introduces an example in the Tutorial section on how to launch a WorkChain through the REST API.
This example was adapted from the GSOC 2021 Report by Ninad Bhat.

2021-12-09 15:33 UTC, ltalirz requested changes
thanks a lot @flavianojs 

Just a couple of suggestions

2021-12-09 15:33 UTC, ltalirz commented on docs/source/user_guide/tutorial.md
> +You will also need a HTTP operator that allows you to send attachments (which will constitute what is called the `Request Body`). Here are two options:
```suggestion
You will also need a tool to make HTTP requests. Here are two options:
```

2021-12-09 15:33 UTC, ltalirz commented on docs/source/user_guide/tutorial.md
> +**Option 1: HTTPie**
```suggestion
**Option 1: HTTPie command line tool**
```

2021-12-09 15:33 UTC, ltalirz commented on docs/source/user_guide/tutorial.md
> +**Option 2: [Resquests library](https://docs.python-requests.org/en/latest/) (all python approach)**
```suggestion
**Option 2: [`requests` python library](https://docs.python-requests.org/en/latest/) (all python approach)**
```

2021-12-09 15:33 UTC, ltalirz commented on docs/source/user_guide/tutorial.md
> +```python
```suggestion
```json
```

This applies to all requests

2021-12-09 15:33 UTC, ltalirz commented on docs/source/user_guide/tutorial.md
> +We are creating two integers with values 6 and 3. Below is the example for posting orm.Int object with value 6.
```suggestion
We are creating two integers with values 6 and 3. Below is the example for posting an `orm.Int` object with value 6.
```

2021-12-09 15:33 UTC, ltalirz commented on docs/source/user_guide/tutorial.md
> +Similarly, we created another orm.Int object of value 3. The retrieved UUID was “29ff3e11-5165-46db-84b0-d85620d0b972”.
```suggestion
Similarly, we created another `orm.Int` object of value 3. The retrieved UUID was “29ff3e11-5165-46db-84b0-d85620d0b972”.
```

2021-12-09 15:33 UTC, ltalirz commented on docs/source/user_guide/tutorial.md
> +print( response.text )
Maybe use `response.json()` instead

2021-12-09 15:33 UTC, ltalirz commented on docs/source/user_guide/tutorial.md
> +The process status can be retrieved from the response.
```suggestion
The process status is reported in `response.json()["attributes"]["process_state"]`.
```

2021-12-09 16:19 UTC, flavianojs commented on docs/source/user_guide/tutorial.md
> +```python
```suggestion
```json
```

2021-12-09 16:19 UTC, flavianojs commented on docs/source/user_guide/tutorial.md
> +   ```python
```suggestion
   ```json 
```

2021-12-09 16:20 UTC, flavianojs commented on docs/source/user_guide/tutorial.md
> +   ```python
```suggestion
   ```json
```

2021-12-09 16:20 UTC, flavianojs commented on docs/source/user_guide/tutorial.md
> +```python
```suggestion
```json
```

2021-12-09 16:21 UTC, flavianojs commented on docs/source/user_guide/tutorial.md
> +print( response.text )
```suggestion
print( response.json )
```

2021-12-09 16:22 UTC, flavianojs commented on docs/source/user_guide/tutorial.md
> +```python
```suggestion
```json
```

2021-12-09 16:22 UTC, flavianojs commented on docs/source/user_guide/tutorial.md
> +```python
```suggestion
```json
```

2021-12-09 17:32 UTC, ltalirz commented
Thanks for the fixes @flavianojs , as well as for pointing out the authentication issue over slack.

The easiest steps for authentication are:

1. Go to http://127.0.0.1:8000/docs
2. Click on "Authorize"
3. Use username "johndoe@example.com" and password "secret"
4. Log in

You can now use the Swagger Javascript client to send requests to the API (which we should probably add as the first way of doing things in the tutorial).

What this does is it will add a `Authorization: Bearer eyJhbGciOiJIUzI1NiIs...` header to all requests.

You can also authenticate from the python API but let's not include that in the tutorial.

2021-12-19 16:02 UTC, ltalirz commented
@flavianojs Are you still going to add the bit on the authentication or should I go ahead and merge this?

2021-12-20 17:41 UTC, flavianojs commented
> @flavianojs Are you still going to add the bit on the authentication or should I go ahead and merge this?

Thanks, Leo. Give me one day or two.

2021-12-23 10:06 UTC, flavianojs commented
Hi @ltalirz, would you have a look at it now? Cheers.

2022-01-01 19:32 UTC, ltalirz approved these changes
looks great, thanks a lot @flavianojs and happy new year!

2022-01-01 19:33 UTC, merged