Add `/server/*` endpoint group to REST API
aiidateam/aiida-restapi pull request #76
Opened 2024-11-21 11:33 UTC by agoscinski

This includes the implementation of the endpoints `/server/info` and `/server/endpoints`. There are some slight changes over the old REST API:

* The endpoint `/server/` has been moved to `/server/info`
* The key name in the response of endpoint `/server/endpoints` has been changed from `available_endpoints` to `endpoints`
* The strings in the response of endpoint `/server/endpoints` has been splitted up into a dictionary with keys "methods", "group", "path" that contain the same information as the strings but structured

2024-11-22 12:31 UTC, eimrek requested changes
When i test, currently i get the version in the url path like

```
{'endpoints': [{'path': '0.1.0a1/token',
   'group': 'token',
   'methods': ['POST']},
  {'path': '0.1.0a1/auth/me/', 'group': 'auth', 'methods': ['GET']},
  {'path': '0.1.0a1/computers', 'group': 'computers', 'methods': ['GET']},
  {'path': '0.1.0a1/computers/projectable_properties',
```

It's currently wrong (as we don't server under that subpath), and probably we want just the major version, right? i.e. `{'path': 'v0/token',`

2024-11-22 12:31 UTC, eimrek commented on tests/conftest.py
> +def calcjob_nodes():
What is this for? it's not used, right?

2025-12-01 06:06 UTC, edan-bainglass commented
> When i test, currently i get the version in the url path like
> 
> ```
> {'endpoints': [{'path': '0.1.0a1/token',
>    'group': 'token',
>    'methods': ['POST']},
>   {'path': '0.1.0a1/auth/me/', 'group': 'auth', 'methods': ['GET']},
>   {'path': '0.1.0a1/computers', 'group': 'computers', 'methods': ['GET']},
>   {'path': '0.1.0a1/computers/projectable_properties',
> ```
> 
> It's currently wrong (as we don't server under that subpath), and probably we want just the major version, right? i.e. `{'path': 'v0/token',`

@eimrek seems like the `API_CONFIG`

```python
API_CONFIG = {
    'PREFIX': version('aiida_restapi'),  # prefix for all URLs
    'VERSION': '0.1.0a',
}
```

should be

```python
API_CONFIG = {
    'PREFIX': 'api/v0',  # prefix for all URLs
    'VERSION': version('aiida_restapi'),
}
```

but are you suggesting only `v0` for the `PREFIX`?

2025-12-01 06:16 UTC, edan-bainglass commented on tests/conftest.py
> +def calcjob_nodes():
@agoscinski more so, ware changes in conftest.py necessary for this PR? Seems unrelated.

2025-12-01 06:21 UTC, edan-bainglass commented
> ```python
> API_CONFIG = {
>     'PREFIX': 'api/v0',  # prefix for all URLs
>     'VERSION': version('aiida_restapi'),
> }
> ```

@eimrek actually, it is unclear to me why we add the prefix in this hardcoded fashion. I would leave it as an API-spinning argument, e.g., `aiida-restapi start --root /api/v0` or something similar (or maybe an environment variable). More flexible, no?

2025-12-01 06:30 UTC, edan-bainglass commented on aiida_restapi/config.py
> +DOWNLOAD_CHUNK_SIZE = 1024
I suppose there was a reason for this, but at least in this PR, it goes unused. Perhaps best to introduce it in a separate PR. @agoscinski can you record here the reason for adding it here?

2025-12-01 09:46 UTC, agoscinski commented on tests/conftest.py
> +def calcjob_nodes():
probably not needed, some code from another PR

2025-12-19 14:21 UTC, edan-bainglass commented
Closing this in favor of #97

2025-12-19 14:21 UTC, closed without merging